name: Auto commit

on:
  push:
    branches:
      - master

  schedule:
    - cron: "0 */2 * * 1"  # Senin tiap 2 jam
    - cron: "0 */3 * * 2"  # Selasa tiap 3 jam
    - cron: "0 */2 * * 3"  # Rabu tiap 2 jam
    - cron: "0 */5 * * 4"  # Kamis tiap 5 jam
    - cron: "0 */2 * * 5"  # Jumat tiap 2 jam
    - cron: "0 */4 * * 6"  # Sabtu tiap 4 jam
    - cron: "0 */8 * * 0"  # Minggu tiap 8 jam


  workflow_dispatch:

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update LAST_UPDATED
        run: |
          echo "Updated at $(date -u '+%Y-%m-%d %H:%M:%S UTC')" > LAST_UPDATED

      - name: Commit changes
        run: |
          git config --local user.email "subhannrizkii@gmail.com"
          git config --local user.name "subhanrizki"

          git add LAST_UPDATED

          arr[0]="chore(bot): 😂 auto commit"
          arr[1]="chore(bot): 😱 auto commit"
          arr[2]="chore(bot): 👿 auto commit"
          arr[3]="chore(bot): 💩 auto commit"
          arr[4]="chore(bot): 🙏 auto commit"
          arr[5]="chore(bot): 🙈 auto commit"
          arr[6]="chore(bot): 🐐 auto commit"
          arr[7]="chore(bot): 🤖 auto commit"
          arr[8]="chore(bot): 🟩 auto commit"
          arr[9]="chore(bot): 👻 auto commit"

          rand=$((RANDOM % 10))

          git commit -m "${arr[$rand]}" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
